### ISSUE TITLE
Create Mobile Nav-5

### ISSUE THREAD

**Issue by Rajdip019** [Clueless-Community/web-ui-kit#282] opened 2022-10-17 18:21 UTC
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
![navbar-style-4 navbar-light](https://user-images.githubusercontent.com/91758830/196253253-e264c456-6414-45d9-ae5d-563b744f006d.png)

After building the component please raise a PR with a screenshot of the component and add the component in `Navbar/nav-mobile/nav-5.html`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by 20RitikSingh** [comment] 2022-10-17 18:53
I want to contribute to this.

**Comment by Rajdip019** [comment] 2022-10-17 18:54
Go ahead. @20RitikSingh

**Comment by rupsha014** [comment] 2022-10-20 19:50
@20RitikSingh are you still working on this issue?

**Comment by rupsha014** [comment] 2022-10-22 18:39
If anybody else wants to work on this issue then please comment.

**Comment by Viren0602** [comment] 2022-10-24 09:08
Hello sir, can you assign this issue to me?

**Comment by Viren0602** [comment] 2022-10-24 11:09
I have raised a PR on issue #282 look over it if you need any changes

**Closed** 2022-10-24 18:56 UTC
Labels: good first issue, hacktoberfest

**Comment by Viren0602** [comment] 2022-10-24 19:08
I was assigned with this issue and I have raised a PR for that but my PR was not accepted and the issue is closed.
